"""create section_of_line, sol_track, sol_track_parameter 2

Revision ID: 10b6c66ee1d3
Revises: 5e7f17638bc0
Create Date: 2025-07-04 21:47:50.242276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10b6c66ee1d3'
down_revision: Union[str, None] = '5e7f17638bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section_of_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('validity_date_start', sa.Date(), nullable=True),
    sa.Column('validity_date_end', sa.Date(), nullable=True),
    sa.Column('solim_code', sa.String(), nullable=True),
    sa.Column('sol_line_identification', sa.String(), nullable=True),
    sa.Column('sol_op_start', sa.String(), nullable=True),
    sa.Column('sol_op_end', sa.String(), nullable=True),
    sa.Column('sol_length', sa.Float(), nullable=True),
    sa.Column('sol_nature', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sol_op_end'], ['operational_point.op_id'], ),
    sa.ForeignKeyConstraint(['sol_op_start'], ['operational_point.op_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sol_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_validity_date_start', sa.Date(), nullable=True),
    sa.Column('track_validity_date_end', sa.Date(), nullable=True),
    sa.Column('sol_track_identification', sa.String(), nullable=True),
    sa.Column('sol_track_direction', sa.String(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section_of_line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sol_track_parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.String(), nullable=True),
    sa.Column('is_applicable', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('optional_value', sa.String(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('manual_added', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['sol_track.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sol_track_parameter')
    op.drop_table('sol_track')
    op.drop_table('section_of_line')
    # ### end Alembic commands ###
