"""create text, text_type

Revision ID: 2a3395aa4c83
Revises: dcb165976c4d
Create Date: 2025-07-04 23:24:02.332713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3395aa4c83'
down_revision: Union[str, None] = 'dcb165976c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_text_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project_text',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=100), nullable=False),
    sa.Column('weblink', sa.String(length=1000), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type'], ['project_text_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_to_project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_id'], ['project_text.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'text_id', name='uq_text_to_project')
    )
    op.create_unique_constraint('uq_finve_to_project', 'finve_to_project', ['project_id', 'finve_id'])
    op.create_unique_constraint('uq_project_to_project_group', 'project_to_project_group', ['project_id', 'project_group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_to_project_group', 'project_to_project_group', type_='unique')
    op.drop_constraint('uq_finve_to_project', 'finve_to_project', type_='unique')
    op.drop_table('text_to_project')
    op.drop_table('project_text')
    op.drop_table('project_text_type')
    # ### end Alembic commands ###
