"""changed type of geojson_representation in Project

Revision ID: 391a7c035423
Revises: 6e36d46a5057
Create Date: 2025-08-06 20:43:05.383755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391a7c035423'
down_revision: Union[str, None] = '6e36d46a5057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_document_to_project', 'document_to_project', ['project_id', 'document_id'])
    op.alter_column('project', 'geojson_representation',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # op.create_unique_constraint('uq_project_to_operational_point', 'project_to_operation_point', ['project_id', 'operational_point_id'])
    # op.create_unique_constraint('uq_project_to_section_of_line', 'project_to_section_of_line', ['project_id', 'section_of_line_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_to_section_of_line', 'project_to_section_of_line', type_='unique')
    op.drop_constraint('uq_project_to_operational_point', 'project_to_operation_point', type_='unique')
    op.alter_column('project', 'geojson_representation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint('uq_document_to_project', 'document_to_project', type_='unique')
    # ### end Alembic commands ###
