"""create section_of_line, sol_track, sol_track_parameter

Revision ID: 5e7f17638bc0
Revises: 7d7c39c8e5ae
Create Date: 2025-07-04 21:43:37.711271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e7f17638bc0'
down_revision: Union[str, None] = '7d7c39c8e5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
