"""added id_old to ProjectGroup

Revision ID: 696d5a300023
Revises: 391a7c035423
Create Date: 2025-08-06 22:50:19.758632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696d5a300023'
down_revision: Union[str, None] = '391a7c035423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_document_to_project', 'document_to_project', ['project_id', 'document_id'])
    op.add_column('project_group', sa.Column('id_old', sa.Integer(), nullable=True, comment='old id from the old database, used for migration purposes'))
    op.create_unique_constraint(None, 'project_group', ['id_old'])
    # op.create_unique_constraint('uq_project_to_operational_point', 'project_to_operation_point', ['project_id', 'operational_point_id'])
    # op.create_unique_constraint('uq_project_to_section_of_line', 'project_to_section_of_line', ['project_id', 'section_of_line_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_to_section_of_line', 'project_to_section_of_line', type_='unique')
    op.drop_constraint('uq_project_to_operational_point', 'project_to_operation_point', type_='unique')
    op.drop_constraint(None, 'project_group', type_='unique')
    op.drop_column('project_group', 'id_old')
    op.drop_constraint('uq_document_to_project', 'document_to_project', type_='unique')
    # ### end Alembic commands ###
