"""changed project_number to not unique

Revision ID: 6e36d46a5057
Revises: cff6dfce89a3
Create Date: 2025-08-06 19:03:16.591281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e36d46a5057'
down_revision: Union[str, None] = 'cff6dfce89a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_document_to_project', 'document_to_project', ['project_id', 'document_id'])
    op.alter_column('project', 'project_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('project_project_number_key'), 'project', type_='unique')
    # op.create_unique_constraint('uq_project_to_operational_point', 'project_to_operation_point', ['project_id', 'operational_point_id'])
    # op.create_unique_constraint('uq_project_to_section_of_line', 'project_to_section_of_line', ['project_id', 'section_of_line_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_to_section_of_line', 'project_to_section_of_line', type_='unique')
    op.drop_constraint('uq_project_to_operational_point', 'project_to_operation_point', type_='unique')
    op.create_unique_constraint(op.f('project_project_number_key'), 'project', ['project_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('project', 'project_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('uq_document_to_project', 'document_to_project', type_='unique')
    # ### end Alembic commands ###
