"""create operational_point table

Revision ID: 7d7c39c8e5ae
Revises: 
Create Date: 2025-07-04 21:33:42.018020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7c39c8e5ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('op_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('validity_date_start', sa.Date(), nullable=True),
    sa.Column('validity_date_end', sa.Date(), nullable=True),
    sa.Column('railway_location', sa.String(), nullable=True),
    sa.Column('railway_location_km', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('op_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operational_point')
    # ### end Alembic commands ###
