"""document

Revision ID: bb11748ef321
Revises: 2a3395aa4c83
Create Date: 2025-07-04 23:47:47.190662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb11748ef321'
down_revision: Union[str, None] = '2a3395aa4c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_to_project',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'document_id'),
    sa.UniqueConstraint('project_id', 'document_id', name='uq_document_to_project')
    )
    op.create_table('project_to_operation_point',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('operational_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operational_point_id'], ['operational_point.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'operational_point_id'),
    sa.UniqueConstraint('project_id', 'operational_point_id', name='uq_project_to_operational_point')
    )
    op.create_table('project_to_section_of_line',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('section_of_line_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_of_line_id'], ['section_of_line.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'section_of_line_id'),
    sa.UniqueConstraint('project_id', 'section_of_line_id', name='uq_project_to_section_of_line')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_to_section_of_line')
    op.drop_table('project_to_operation_point')
    op.drop_table('document_to_project')
    op.drop_table('document')
    # ### end Alembic commands ###
