"""added old_id to project

Revision ID: cff6dfce89a3
Revises: bb11748ef321
Create Date: 2025-08-06 18:56:46.124253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff6dfce89a3'
down_revision: Union[str, None] = 'bb11748ef321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_document_to_project', 'document_to_project', ['project_id', 'document_id'])
    op.add_column('project', sa.Column('old_id', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('superior_project_old_id', sa.Integer(), nullable=True))
    # op.create_unique_constraint('uq_project_to_operational_point', 'project_to_operation_point', ['project_id', 'operational_point_id'])
    # op.create_unique_constraint('uq_project_to_section_of_line', 'project_to_section_of_line', ['project_id', 'section_of_line_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_to_section_of_line', 'project_to_section_of_line', type_='unique')
    op.drop_constraint('uq_project_to_operational_point', 'project_to_operation_point', type_='unique')
    op.drop_column('project', 'superior_project_old_id')
    op.drop_column('project', 'old_id')
    op.drop_constraint('uq_document_to_project', 'document_to_project', type_='unique')
    # ### end Alembic commands ###
