"""create budget, finve

Revision ID: dcb165976c4d
Revises: 1c625eeae985
Create Date: 2025-07-04 23:13:01.721837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcb165976c4d'
down_revision: Union[str, None] = '1c625eeae985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finve',
    sa.Column('id', sa.Integer(), server_default='2000', autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('starting_year', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_original', sa.Integer(), nullable=True),
    sa.Column('temporary_finve_number', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('short_name', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('plot_only_superior_projects', sa.Boolean(), nullable=True, comment='if true, only projects that have no superior project is plotted in frontend'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_year', sa.Integer(), nullable=False),
    sa.Column('lfd_nr', sa.String(length=100), nullable=True),
    sa.Column('fin_ve', sa.Integer(), nullable=True),
    sa.Column('bedarfsplan_number', sa.String(length=100), nullable=True),
    sa.Column('sammel_finve', sa.Boolean(), nullable=True),
    sa.Column('starting_year', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_original', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_last_year', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_actual', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_actual_third_parties', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_actual_equity', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_actual_891_01', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_actual_891_02', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_actual_891_03', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_actual_891_04', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_actual_891_91', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_actual_891_72', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_actual_891_11', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_actual_891_21', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_actual_861_01', sa.Integer(), nullable=True),
    sa.Column('delta_previous_year', sa.Integer(), nullable=True),
    sa.Column('delta_previous_year_relativ', sa.Float(), nullable=True),
    sa.Column('delta_previous_year_reasons', sa.Text(), nullable=True),
    sa.Column('spent_two_years_previous', sa.Integer(), nullable=True),
    sa.Column('spent_two_years_previous_third_parties', sa.Integer(), nullable=True),
    sa.Column('spent_two_years_previous_equity', sa.Integer(), nullable=True),
    sa.Column('spent_two_years_previous_891_01', sa.Integer(), nullable=True),
    sa.Column('spent_two_years_previous_891_02', sa.Integer(), nullable=True),
    sa.Column('spent_two_years_previous_891_03', sa.Integer(), nullable=True),
    sa.Column('spent_two_years_previous_891_04', sa.Integer(), nullable=True),
    sa.Column('spent_two_years_previous_891_91', sa.Integer(), nullable=True),
    sa.Column('spent_two_years_previous_891_72', sa.Integer(), nullable=True),
    sa.Column('spent_two_years_previous_891_11', sa.Integer(), nullable=True),
    sa.Column('spent_two_years_previous_891_21', sa.Integer(), nullable=True),
    sa.Column('spent_two_years_previous_861_01', sa.Integer(), nullable=True),
    sa.Column('allowed_previous_year', sa.Integer(), nullable=True),
    sa.Column('allowed_previous_year_third_parties', sa.Integer(), nullable=True),
    sa.Column('allowed_previous_year_equity', sa.Integer(), nullable=True),
    sa.Column('allowed_previous_year_891_01', sa.Integer(), nullable=True),
    sa.Column('allowed_previous_year_891_02', sa.Integer(), nullable=True),
    sa.Column('allowed_previous_year_891_03', sa.Integer(), nullable=True),
    sa.Column('allowed_previous_year_891_04', sa.Integer(), nullable=True),
    sa.Column('allowed_previous_year_891_91', sa.Integer(), nullable=True),
    sa.Column('allowed_previous_year_891_72', sa.Integer(), nullable=True),
    sa.Column('allowed_previous_year_891_11', sa.Integer(), nullable=True),
    sa.Column('allowed_previous_year_891_21', sa.Integer(), nullable=True),
    sa.Column('allowed_previous_year_861_01', sa.Integer(), nullable=True),
    sa.Column('spending_residues', sa.Integer(), nullable=True),
    sa.Column('spending_residues_891_01', sa.Integer(), nullable=True),
    sa.Column('spending_residues_891_02', sa.Integer(), nullable=True),
    sa.Column('spending_residues_891_03', sa.Integer(), nullable=True),
    sa.Column('spending_residues_891_04', sa.Integer(), nullable=True),
    sa.Column('spending_residues_891_91', sa.Integer(), nullable=True),
    sa.Column('spending_residues_891_72', sa.Integer(), nullable=True),
    sa.Column('spending_residues_891_11', sa.Integer(), nullable=True),
    sa.Column('spending_residues_891_21', sa.Integer(), nullable=True),
    sa.Column('spending_residues_861_01', sa.Integer(), nullable=True),
    sa.Column('year_planned', sa.Integer(), nullable=True),
    sa.Column('year_planned_third_parties', sa.Integer(), nullable=True),
    sa.Column('year_planned_equity', sa.Integer(), nullable=True),
    sa.Column('year_planned_891_01', sa.Integer(), nullable=True),
    sa.Column('year_planned_891_02', sa.Integer(), nullable=True),
    sa.Column('year_planned_891_03', sa.Integer(), nullable=True),
    sa.Column('year_planned_891_04', sa.Integer(), nullable=True),
    sa.Column('year_planned_891_91', sa.Integer(), nullable=True),
    sa.Column('year_planned_891_72', sa.Integer(), nullable=True),
    sa.Column('year_planned_891_11', sa.Integer(), nullable=True),
    sa.Column('year_planned_891_21', sa.Integer(), nullable=True),
    sa.Column('year_planned_861_01', sa.Integer(), nullable=True),
    sa.Column('next_years', sa.Integer(), nullable=True),
    sa.Column('next_years_third_parties', sa.Integer(), nullable=True),
    sa.Column('next_years_equity', sa.Integer(), nullable=True),
    sa.Column('next_years_891_01', sa.Integer(), nullable=True),
    sa.Column('next_years_891_02', sa.Integer(), nullable=True),
    sa.Column('next_years_891_03', sa.Integer(), nullable=True),
    sa.Column('next_years_891_04', sa.Integer(), nullable=True),
    sa.Column('next_years_891_91', sa.Integer(), nullable=True),
    sa.Column('next_years_891_72', sa.Integer(), nullable=True),
    sa.Column('next_years_891_11', sa.Integer(), nullable=True),
    sa.Column('next_years_891_21', sa.Integer(), nullable=True),
    sa.Column('next_years_861_01', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fin_ve'], ['finve.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('budgets_year_and_finve_uindex', 'budgets', ['budget_year', 'fin_ve'], unique=True)
    op.create_table('finve_to_project',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('finve_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finve_id'], ['finve.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'finve_id')
    )
    op.create_table('project_to_project_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_group_id'], ['project_group.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_to_project_group')
    op.drop_table('finve_to_project')
    op.drop_index('budgets_year_and_finve_uindex', table_name='budgets')
    op.drop_table('budgets')
    op.drop_table('project_group')
    op.drop_table('finve')
    # ### end Alembic commands ###
