/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/route/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Route */
        post: operations["get_route_api_v1_route__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read All Projects
         * @description Retrieve all projects.
         */
        get: operations["read_all_projects_api_v1_projects__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Project */
        get: operations["read_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/project_groups/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Project Groups */
        get: operations["read_project_groups_api_v1_project_groups__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/project_groups/{group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Project Group */
        get: operations["read_project_group_api_v1_project_groups__group_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProjectGroupSchema */
        ProjectGroupSchema: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
            /** Short Name */
            short_name: string;
            /** Description */
            description?: string | null;
            /**
             * Public
             * @default false
             */
            public: boolean;
            /**
             * Color
             * @default #FF0000
             */
            color: string;
            /**
             * Plot Only Superior Projects
             * @default true
             */
            plot_only_superior_projects: boolean;
            /** Id Old */
            id_old?: number | null;
            /**
             * Projects
             * @description List of projects associated with this project group
             */
            projects?: components["schemas"]["ProjectSchema"][];
        };
        /** ProjectSchema */
        ProjectSchema: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
            /** Project Number */
            project_number?: string | null;
            /** Superior Project Id */
            superior_project_id?: number | null;
            /** Old Id */
            old_id?: number | null;
            /** Superior Project Old Id */
            superior_project_old_id?: number | null;
            /** Description */
            description?: string | null;
            /** Justification */
            justification?: string | null;
            /**
             * Effects Passenger Long Rail
             * @default false
             */
            effects_passenger_long_rail: boolean | null;
            /**
             * Effects Passenger Local Rail
             * @default false
             */
            effects_passenger_local_rail: boolean | null;
            /**
             * Effects Cargo Rail
             * @default false
             */
            effects_cargo_rail: boolean | null;
            /** Length */
            length: number | null;
            /**
             * Nbs
             * @default false
             */
            nbs: boolean;
            /**
             * Abs
             * @default false
             */
            abs: boolean;
            /**
             * Elektrification
             * @default false
             */
            elektrification: boolean;
            /**
             * Charging Station
             * @default false
             */
            charging_station: boolean | null;
            /**
             * Small Charging Station
             * @default false
             */
            small_charging_station: boolean | null;
            /**
             * Second Track
             * @default false
             */
            second_track: boolean;
            /**
             * Third Track
             * @default false
             */
            third_track: boolean;
            /**
             * Fourth Track
             * @default false
             */
            fourth_track: boolean;
            /**
             * Curve
             * @default false
             */
            curve: boolean;
            /**
             * Platform
             * @default false
             */
            platform: boolean;
            /**
             * Junction Station
             * @default false
             */
            junction_station: boolean;
            /** Number Junction Station */
            number_junction_station: number | null;
            /**
             * Overtaking Station
             * @default false
             */
            overtaking_station: boolean;
            /** Number Overtaking Station */
            number_overtaking_station: number | null;
            /**
             * Double Occupancy
             * @default false
             */
            double_occupancy: boolean;
            /**
             * Block Increase
             * @default false
             */
            block_increase: boolean;
            /**
             * Flying Junction
             * @default false
             */
            flying_junction: boolean;
            /**
             * Tunnel Structural Gauge
             * @default false
             */
            tunnel_structural_gauge: boolean;
            /**
             * Increase Speed
             * @default false
             */
            increase_speed: boolean;
            /** New Vmax */
            new_vmax: number | null;
            /**
             * Level Free Platform Entrance
             * @default false
             */
            level_free_platform_entrance: boolean;
            /**
             * Etcs
             * @default false
             */
            etcs: boolean;
            /** Etcs Level */
            etcs_level: number | null;
            /**
             * Station Railroad Switches
             * @default false
             */
            station_railroad_switches: boolean | null;
            /**
             * New Station
             * @default false
             */
            new_station: boolean | null;
            /**
             * Depot
             * @default false
             */
            depot: boolean | null;
            /**
             * Battery
             * @default false
             */
            battery: boolean | null;
            /**
             * H2
             * @default false
             */
            h2: boolean | null;
            /**
             * Efuel
             * @default false
             */
            efuel: boolean | null;
            /**
             * Closure
             * @default false
             */
            closure: boolean | null;
            /**
             * Optimised Electrification
             * @default false
             */
            optimised_electrification: boolean | null;
            /**
             * Filling Stations Efuel
             * @default false
             */
            filling_stations_efuel: boolean | null;
            /**
             * Filling Stations H2
             * @default false
             */
            filling_stations_h2: boolean | null;
            /**
             * Filling Stations Diesel
             * @default false
             */
            filling_stations_diesel: boolean | null;
            /**
             * Filling Stations Count
             * @default 0
             */
            filling_stations_count: number | null;
            /**
             * Sanierung
             * @default false
             */
            sanierung: boolean | null;
            /**
             * Sgv740M
             * @default false
             */
            sgv740m: boolean | null;
            /**
             * Railroad Crossing
             * @default false
             */
            railroad_crossing: boolean | null;
            /**
             * New Estw
             * @default false
             */
            new_estw: boolean | null;
            /**
             * New Dstw
             * @default false
             */
            new_dstw: boolean | null;
            /**
             * Noise Barrier
             * @default false
             */
            noise_barrier: boolean | null;
            /**
             * Overpass
             * @default false
             */
            overpass: boolean | null;
            /**
             * Buffer Track
             * @default false
             */
            buffer_track: boolean | null;
            /**
             * Gwb
             * @default false
             */
            gwb: boolean | null;
            /**
             * Simultaneous Train Entries
             * @default false
             */
            simultaneous_train_entries: boolean | null;
            /**
             * Tilting
             * @default false
             */
            tilting: boolean | null;
            /** Geojson Representation */
            geojson_representation?: string | null;
            /** Centroid */
            centroid?: unknown | null;
        };
        /** RouteRequest */
        RouteRequest: {
            /** Start Op */
            start_op: string;
            /** End Op */
            end_op: string;
        };
        /** RouteResponse */
        RouteResponse: {
            /** Sectionofline Ids */
            sectionofline_ids: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_route_api_v1_route__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RouteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_all_projects_api_v1_projects__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSchema"][];
                };
            };
        };
    };
    read_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_project_groups_api_v1_project_groups__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectGroupSchema"][];
                };
            };
        };
    };
    read_project_group_api_v1_project_groups__group_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
