from sqlalchemy import Column, Integer, String, Text, Float, Boolean, ForeignKey

from dashboard_backend.models.base import Base

class BvwpProjectData(Base):
    __tablename__ = 'bvwp_project_data'

    id = Column(Integer, primary_key=True)
    project_id = Column(Integer, ForeignKey('project.id', onupdate='CASCADE', ondelete='CASCADE'), nullable=False)
    bvwp_alternatives = Column(Text, default=None)
    nkv = Column(Float)
    priority = Column(String(100))
    reason_priority = Column(Text)

    # traffic forecast
    # # passenger
    relocation_car_to_rail = Column(Float)
    relocation_rail_to_car = Column(Float)
    relocation_air_to_rail = Column(Float)
    induced_traffic = Column(Float)
    delta_car_km = Column(Float)
    delta_km_rail = Column(Float)
    delta_rail_running_time = Column(Float)
    delta_rail_km_rail = Column(Float)
    delta_rail_km_car_to_rail = Column(Float)
    delta_rail_km_rail_to_car = Column(Float)
    delta_rail_km_air_to_rail = Column(Float)
    delta_rail_km_induced = Column(Float)
    delta_travel_time_rail = Column(Float)
    delta_travel_time_car_to_rail = Column(Float)
    delta_travel_time_rail_to_car = Column(Float)
    delta_travel_time_air_to_rail = Column(Float)
    delta_travel_time_induced = Column(Float)

    # # cargo
    relocation_truck_to_rail = Column(Float)
    relocation_ship_to_rail = Column(Float)
    delta_truck_km = Column(Float)
    delta_truck_count = Column(Float)
    delta_rail_cargo_count = Column(Float)
    delta_rail_cargo_running_time = Column(Float)
    delta_rail_cargo_km_lkw_to_rail = Column(Float)
    delta_rail_cargo_km_ship_to_rail = Column(Float)
    delta_rail_cargo_time_rail = Column(Float)
    delta_rail_cargo_time_lkw_to_rail = Column(Float)
    delta_rail_cargo_time_ship_to_rail = Column(Float)

    # use calculation
    # # passenger
    use_change_operation_cost_car_yearly = Column(Float)
    use_change_operating_cost_rail_yearly = Column(Float)
    use_change_operating_cost_air_yearly = Column(Float)
    use_change_pollution_car_yearly = Column(Float)
    use_change_pollution_rail_yearly = Column(Float)
    use_change_pollution_air_yearly = Column(Float)
    use_change_safety_car_yearly = Column(Float)
    use_change_safety_rail_yearly = Column(Float)
    use_change_travel_time_rail_yearly = Column(Float)
    use_change_travel_time_induced_yearly = Column(Float)
    use_change_travel_time_pkw_yearly = Column(Float)
    use_change_travel_time_air_yearly = Column(Float)
    use_change_travel_time_less_2min_yearly = Column(Float)
    use_change_implicit_benefit_induced_yearly = Column(Float)
    use_change_implicit_benefit_pkw_yearly = Column(Float)
    use_change_implicit_benefit_air_yearly = Column(Float)
    use_sum_passenger_yearly = Column(Float)

    use_change_operation_cost_car_present_value = Column(Float)
    use_change_operating_cost_rail_present_value = Column(Float)
    use_change_operating_cost_air_present_value = Column(Float)
    use_change_pollution_car_present_value = Column(Float)
    use_change_pollution_rail_present_value = Column(Float)
    use_change_pollution_air_present_value = Column(Float)
    use_change_safety_car_present_value = Column(Float)
    use_change_safety_rail_present_value = Column(Float)
    use_change_travel_time_rail_present_value = Column(Float)
    use_change_travel_time_induced_present_value = Column(Float)
    use_change_travel_time_pkw_present_value = Column(Float)
    use_change_travel_time_air_present_value = Column(Float)
    use_change_travel_time_less_2min_present_value = Column(Float)
    use_change_implicit_benefit_induced_present_value = Column(Float)
    use_change_implicit_benefit_pkw_present_value = Column(Float)
    use_change_implicit_benefit_air_present_value = Column(Float)
    use_sum_passenger_present_value = Column(Float)

    # # cargo
    use_change_operating_cost_truck_yearly = Column(Float)
    use_change_operating_cost_rail_cargo_yearly = Column(Float)
    use_change_operating_cost_ship_yearly = Column(Float)
    use_change_pollution_truck_yearly = Column(Float)
    use_change_pollution_rail_cargo_yearly = Column(Float)
    use_change_pollution_ship_yearly = Column(Float)
    use_change_safety_truck_yearly = Column(Float)
    use_change_safety_rail_cargo_yearly = Column(Float)
    use_change_safety_ship_yearly = Column(Float)
    use_change_running_time_rail_yearly = Column(Float)
    use_change_running_time_lkw_yearly = Column(Float)
    use_change_running_time_ship_yearly = Column(Float)
    use_change_implicit_benefit_truck_yearly = Column(Float)
    use_change_implicit_benefit_ship_yearly = Column(Float)
    use_change_reliability_yearly = Column(Float)
    use_sum_cargo_yearly = Column(Float)

    use_change_operating_cost_truck_present_value = Column(Float)
    use_change_operating_cost_rail_cargo_present_value = Column(Float)
    use_change_operating_cost_ship_present_value = Column(Float)
    use_change_pollution_truck_present_value = Column(Float)
    use_change_pollution_rail_cargo_present_value = Column(Float)
    use_change_pollution_ship_present_value = Column(Float)
    use_change_safety_truck_present_value = Column(Float)
    use_change_safety_rail_cargo_present_value = Column(Float)
    use_change_safety_ship_present_value = Column(Float)
    use_change_running_time_rail_present_value = Column(Float)
    use_change_running_time_lkw_present_value = Column(Float)
    use_change_running_time_ship_present_value = Column(Float)
    use_change_implicit_benefit_truck_present_value = Column(Float)
    use_change_implicit_benefit_ship_present_value = Column(Float)
    use_change_reliability_present_value = Column(Float)
    use_sum_cargo_present_value = Column(Float)

    # # other use
    use_change_maintenance_cost_yearly = Column(Float)
    use_change_lcc_infrastructure_yearly = Column(Float)
    use_change_noise_intown_yearly = Column(Float)
    use_change_noise_outtown_yearly = Column(Float)
    sum_use_change_yearly = Column(Float)

    use_change_maintenance_cost_present_value = Column(Float)
    use_change_lcc_infrastructure_present_value = Column(Float)
    use_change_noise_intown_present_value = Column(Float)
    use_change_noise_outtown_present_value = Column(Float)
    sum_use_change_present_value = Column(Float)

    bvwp_duration_of_outstanding_planning = Column(Float)
    bvwp_duration_of_build = Column(Float)
    bvwp_duration_operating = Column(Float)

    # environmental data
    bvwp_environmental_impact = Column(String(200))
    delta_nox = Column(Float)
    delta_co = Column(Float)
    delta_co2 = Column(Float)
    delta_hc = Column(Float)
    delta_pm = Column(Float)
    delta_so2 = Column(Float)

    bvwp_sum_use_environment = Column(Float)
    bvwp_sum_environmental_affectedness = Column(String(255))
    bvwp_sum_environmental_affectedness_text = Column(Text)
    noise_new_affected = Column(Float)
    noise_relieved = Column(Float)
    change_noise_outtown = Column(Float)

    area_nature_high_importance = Column(Float)
    area_nature_high_importance_per_km = Column(Float)
    area_nature_high_importance_rating = Column(String(255))
    natura2000_rating = Column(String(255))
    natura2000_not_excluded = Column(Float)
    natura2000_probably = Column(Float)
    ufr_250 = Column(Float)
    ufr_250_per_km = Column(Float)
    ufra_250_rating = Column(String(255))
    bfn_rating = Column(String(255))
    ufr_1000_undissacted_large_area = Column(Float)
    ufr_1000_undissacted_large_area_per_km = Column(Float)
    ufr_1000_undissacted_large_mammals = Column(Float)
    ufr_1000_undissacted_large_mammals_per_km = Column(Float)
    count_undissacted_area = Column(Float)
    count_reconnect_area = Column(Float)
    land_consumption = Column(Float)
    flooding_area = Column(Float)
    flooding_area_per_km = Column(Float)
    flooding_area_rating = Column(String(255))
    water_protection_area = Column(Float)
    water_protection_area_per_km = Column(Float)
    water_protection_area_rating = Column(String(255))
    uzvr = Column(Float)
    uvzr_rating = Column(String(255))
    priortiy_area_landscape_protection = Column(Float)
    priority_area_landscape_protection_per_km = Column(Float)
    priority_area_landscape_protection_rating = Column(String(255))
    environmental_additional_informations = Column(Text)

    # financial bvwp data
    bedarfsplan_nr = Column(Integer)
    planned_total_cost = Column(Float)
    actual_cost = Column(Integer)
    maintenance_cost = Column(Float)
    investment_cost = Column(Float)
    planning_cost = Column(Float)
    capital_service_cost = Column(Float)
    bvwp_planned_cost = Column(Float)
    bvwp_planned_maintenance_cost = Column(Float)
    bvwp_planned_planning_cost = Column(Float)
    bvwp_planned_planning_cost_incurred = Column(Float)
    bvwp_total_budget_relevant_cost = Column(Float)
    bvwp_total_budget_relevant_cost_incurred = Column(Float)
    bvwp_valuation_relevant_cost = Column(Float)
    bvwp_valuation_relevant_cost_pricelevel_2012 = Column(Float)

    bvwp_valuation_relevant_cost_pricelevel_2012_planning_cost = Column(Float)
    bvwp_valuation_relevant_cost_pricelevel_2012_infrastructure_cos = Column(Float)
    bvwp_valuation_relevant_cost_pricelevel_2012_present_value = Column(Float)

    # spatial significance
    bvwp_regional_significance = Column(String(255))
    spatial_significance_overall_result = Column(Text)
    spatial_significance_reasons = Column(Text)
    spatial_significance_street = Column(Text)
    spatial_significance_accessibility_deficits = Column(Text)
    spatial_significance_conclusion = Column(Text)

    # capacity
    bottleneck_elimination = Column(Boolean)
    bvwp_congested_rail_reference_6to9_km = Column(Float)
    bvwp_congested_rail_reference_6to9_perc = Column(Float)
    bvwp_congested_rail_plancase_6to9_km = Column(Float)
    bvwp_congested_rail_plancase_6to9_perc = Column(Float)

    bvwp_congested_rail_reference_9to16_km = Column(Float)
    bvwp_congested_rail_reference_9to16_perc = Column(Float)
    bvwp_congested_rail_plancase_9to16_km = Column(Float)
    bvwp_congested_rail_plancase_9to16_perc = Column(Float)

    bvwp_congested_rail_reference_16to19_km = Column(Float)
    bvwp_congested_rail_reference_16to19_perc = Column(Float)
    bvwp_congested_rail_plancase_16to19_km = Column(Float)
    bvwp_congested_rail_plancase_16to19_perc = Column(Float)

    bvwp_congested_rail_reference_19to22_km = Column(Float)
    bvwp_congested_rail_reference_19to22_perc = Column(Float)
    bvwp_congested_rail_plancase_19to22_km = Column(Float)
    bvwp_congested_rail_plancase_19to22_perc = Column(Float)

    bvwp_congested_rail_reference_22to6_km = Column(Float)
    bvwp_congested_rail_reference_22to6_perc = Column(Float)
    bvwp_congested_rail_plancase_22to6_km = Column(Float)
    bvwp_congested_rail_plancase_22to6_perc = Column(Float)

    bvwp_congested_rail_reference_day_km = Column(Float)
    bvwp_congested_rail_reference_day_perc = Column(Float)
    bvwp_congested_rail_plancase_day_km = Column(Float)
    bvwp_congested_rail_plancase_day_perc = Column(Float)

    bvwp_unscheduled_waiting_period_reference = Column(Float)
    bvwp_unscheduled_waiting_period_plancase = Column(Float)

    bvwp_punctuality_cargo_reference = Column(Float)
    bvwp_delta_punctuality_relativ = Column(Float)
    bvwp_delta_punctuality_absolut = Column(Float)

    # travel time
    traveltime_reduction = Column(Float)
    bvwp_traveltime_examples = Column(String)

    # additional informations
    bvwp_additional_informations = Column(Text)
